staging:
  facebook:
    id: <%= ENV['FACEBOOK_ID'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  google:
    id: <%= ENV['GOOGLE_ID'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  linkedin:
    id: <%= ENV['LINKEDIN_ID'] %>
    secret: <%= ENV['LINKEDIN_SECRET'] %>
  email:
    username: <%= ENV['email_username'] %>
    password: <%= ENV['email_password'] %>

production:
  facebook:
    id: <%= ENV['FACEBOOK_ID'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  google:
    id: <%= ENV['GOOGLE_ID'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  linkedin:
    id: <%= ENV['LINKEDIN_ID'] %>
    secret: <%= ENV['LINKEDIN_SECRET'] %>
  email:
    username: <%= ENV['email_username'] %>
    password: <%= ENV['email_password'] %>

development:
  facebook:
    id: "472903682777717"
    secret: "4879261b8fb5aa966983dbcb942e534c"
  google:
    id: "662955766629-ker183n38a59d9rqgbd8eno9ehk0kvg6.apps.googleusercontent.com"
    secret: "RdFJhD5hc6soMw2OnSpXM-Lx"
  linkedin:
    id: "0futayxxa8pq"
    secret: "Mdtba4VZq1JCCUgs"
  email:
    username: "petya.petinych@gmail.com"
    password: "mintscinnamon02"
    support_address: "petya.petinych@gmail.com"
    subject: "Message"

test:
  facebook:
    id: "id"
    secret: "secret"
  google:
    id: "id"
    secret: "secret"
  linkedin:
    id: "id"
    secret: "secret"
  email:
    username: "username"
    password: "password"
    support_address: "address"
