production:
  facebook:
    id: <%= ENV['FACEBOOK_ID'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  google:
    id: <%= ENV['GOOGLE_ID'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  linkedin:
    id: <%= ENV['LINKEDIN_ID'] %>
    secret: <%= ENV['LINKEDIN_SECRET'] %>
  email:
    host: "smtp.sendgrid.net"
    port: 587
    domain: "http://flockcapital.herokuapp.com/"
    username: "oivoodoo"
    password: "201287ali"
    support_address: "alex.korsak@gmail.com"
  redis:
    url: <%= ENV['REDISTOGO_URL'] %>

development:
  facebook:
    id: "217873215035447"
    secret: "4e2d3c9835e99d8dc7c93d62cc16d159"
  google:
    id: "662955766629-ker183n38a59d9rqgbd8eno9ehk0kvg6.apps.googleusercontent.com"
    secret: "RdFJhD5hc6soMw2OnSpXM-Lx"
  linkedin:
    id: "0futayxxa8pq"
    secret: "Mdtba4VZq1JCCUgs"
  email:
    host: "smtp.gmail.com"
    port: 587
    domain: "gmail.com"
    username: "petya.petinych@gmail.com"
    password: "mintscinnamon02"
    support_address: "petya.petinych@gmail.com"
    subject: "Message"
  redis:
    url: "redis://127.0.0.1:6379/"

test:
  facebook:
    id: "id"
    secret: "secret"
  google:
    id: "id"
    secret: "secret"
  linkedin:
    id: "id"
    secret: "secret"
  email:
    host: "smtp.test.com"
    port: 587
    domain: "test.com"
    username: "username"
    password: "password"
    support_address: "address"
  redis:
    url: "redis://127.0.0.1:6379/"

